language: python

python:
  - 3.8

dist: xenial

stages:
  - test-links
  - build
  - name: deploy
    if: branch = main  # Deploy only on main commits

install:
  - pip install pipenv
  - pipenv install

jobs:
  include:
    - stage: test-links
      script: pipenv run make linkcheck
    - stage: build
      script: pipenv run make html
    - stage: deploy
      script: pipenv run make html
      deploy:
        provider: pages
        cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local_dir: docs/html
        on:
          branch: main
